import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    position: 'relative',
    height: '100%',
    backgroundColor: '#f8830a',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  btnClose: {
    zIndex: 1,
    position: 'absolute',
    left: '5%',
    bottom: '3%',
    width: 30,
    height: 30,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 7,
    borderColor: '#f8830a',
    borderWidth: 1.5,
    shadowColor: '#000',
    shadowRadius: 2,
    shadowOpacity: 0.2,
    shadowOffset: { width: 3, height: 3 },
    backgroundColor: '#fff',
  },
  textClose: {
    fontSize: 15,
    color: '#f8830a',
  },
  contentInfo: {
    marginTop: 10,
    padding: 15,
    width: '90%',
    minHeight: '40%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    shadowColor: '#000',
    shadowRadius: 2,
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 0 },
    backgroundColor: '#fff',
  },
  contentInfoChild: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  textCode: {
    fontSize: 42,
    color: '#f8830a',
  },
  textDescription: {
    fontSize: 30,
    textTransform: 'capitalize',
    textAlign: 'center',
    color: '#808080',
  },
  textLocation: {
    flex: 3,
    fontSize: 22,
    textAlign: 'center',
    color: '#a9a7a7',
  },
  textUnd: {
    flex: 1.5,
    fontSize: 22,
    textAlign: 'center',
    color: '#f8860dbb',
  },
  contentQuantity: {
    marginTop: 5,
    width: 120,
    minHeight: 120,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#3b9216',
    borderRadius: 100,
  },
  textQuantity: {
    fontSize: 30,
  },
  textInput: {
    marginTop: 10,
    marginBottom: 10,
    width: '90%',
    height: 80,
    borderColor: '#ededed',
    borderRadius: 10,
    borderWidth: 2,
    textAlign: 'center',
    fontSize: 30,
    backgroundColor: '#fff',
  },
});
